version: 2
project_name: checksec

release:
  prerelease: auto
  extra_files:
    - glob: dist/*.sig
    - glob: dist/*.pub

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - CGO_ENABLED=0

builds:
  - id: core
    binary: checksec
    main: ./main.go
    buildmode: "pie"
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .Commit }}"
      - -X "main.date={{ .Date }}"
      - -extldflags "-Wl,-z,relro,-z,now,-z,noexecstack"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

sboms:
- id: checksec
  documents:
    - "${artifact}.spdx.sbom.json"
  cmd: syft
  args: ["$artifact", "--output", "cyclonedx-json=$document"]
  artifacts: binary
