project_name: checksec

builds:
  - id: linux
    binary: checksec
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .Commit }}"
      - -X "main.date={{ .Date }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
    #  - amd64
      - arm64

  - id: darwin
    binary: checksec
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .Commit }}"
      - -X "main.date={{ .Date }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
    #  - amd64
      - arm64

  # - id: windows
  #   binary: checksec
  #   main: ./main.go
  #   ldflags:
  #     - -s -w
  #     - -X "main.version={{ .Version }}"
  #     - -X "main.commit={{ .Commit }}"
  #     - -X "main.date={{ .Date }}"
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
  #     - arm64
  #   ldflags:
  #     - -buildmode=exe
