repos:
- repo: local
  hooks:
  - id: enable_hooks
    name: enable git hooks
    entry: bash ./hack/enable-git-hooks.sh
    language: system
    pass_filenames: false
  - id: go-test
    name: Run Go tests
    entry: go test ./...
    language: system
    pass_filenames: false
  - id: go-fmt
    name: gofmt (write)
    entry: bash -c 'gofmt -s -w "$@"'
    language: system
    types: [go]
  - id: go-vet
    name: go vet
    entry: bash -c 'go vet ./...'
    language: system
    pass_filenames: false
  - id: go-mod-tidy
    name: go mod tidy
    entry: bash -c 'go mod tidy -v'
    language: system
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: debug-statements
  - id: forbid-new-submodules
  - id: mixed-line-ending
- repo: https://github.com/fauust/pre-commit-shell
  rev: v1.1
  hooks:
  - id: shfmt
    args: ["-sr", "-i", "2", "-ci", "-w"]
  - id: shellcheck
    files: ^checksec$
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/sirosen/fix-smartquotes
  rev: 0.2.0
  hooks:
  - id: fix-smartquotes
