name: docker-compose-test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: render-checksec
        run: |
          pip install pre-commit
          mkdir ${HOME}/bin
          curl -Lo ${HOME}/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64
          chmod +x ${HOME}/bin/shfmt
          export PATH=${PATH}:${HOME}/bin
          pre-commit run --all-files
          git status
          if [[ ! -z $(git status --porcelain) ]]; then
            echo "source file differs, checksec needs build"
            exit 1
          fi
      - name: ubuntu checksec
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose run checksec-ubuntu
